ALTER TABLE users ADD COLUMN password_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;
ALTER TABLE users ADD COLUMN email TEXT UNIQUE;
ALTER TABLE users ADD COLUMN about TEXT;
ALTER TABLE users ADD COLUMN nationality CHAR(2);
ALTER TABLE users ADD COLUMN systems TEXT[];
